### ISSUE TITLE
0.1.13 regression on excluded

### ISSUE THREAD

**Issue by pcause** [Leonezz/obsidian-tasks-calendar-wrapper#24] opened 2023-05-28 11:02 UTC
installed and i now see tasks that are in my excluded folders and they are still shown in the options as excluded folder.  in a sub-folder of excluded folder which you had previously fixed to get working.

**Comment by Leonezz** [comment] 2023-05-28 12:52
Can confirm, there are serious issue with the option system, they do not take effect sometimes.

**Comment by Leonezz** [comment] 2023-05-28 13:00
I have make some fix to this issue, however, I have no clue why the view does not load all the items on opening of obisdian, and the options take effect only after some modifications are made to the files in the valut or plugin options.

**Comment by pcause** [comment] 2023-05-28 14:12
just tried 0.1.14 and still broken.  loaded, restarted and now i get nothing displayed.  NOTHING AT ALL.  clicked focus on today on or off no difference.  no filter selected.  I had accidentally turned off enable counters on filter panel.  when i turn on again, i get the items from the excluded folders.

if it helps I have 2 folders listed, comma separated.  basically:

vault/me/templates,vault/me/tests

and both are folders with subfolder.  should skip all tasks in the folders and their subfolders.

**Comment by Leonezz** [comment] 2023-05-28 14:35
> 

yes it displays nothing on start, that is also an issue I am trying to resolve recently, unfortunately I have no clue yet. But if you trigger the re-renderring event by modify files or options, it should be back normal.

**Comment by MSBack** [comment] 2023-05-28 18:56
I have the same issue, can't see anything and can't add tasks to inbox file or the daily note. When I try to change settings or add a task, the whole Tasks Calendar Wrapper sidebar tab becomes blank until I reopen it.

**Comment by YIRU69** [comment] 2023-05-29 00:48
Updated to version 0.14 and encountered the same issue. Upon testing, it was found that the settings in the 'Start Plugin' section were not functioning properly. The issue was only resolved after I switched to the 'Forward past from past' option

**Comment by Leonezz** [comment] 2023-05-29 02:48
@pcause @MSBack @YIRU69 , I think soma major changes are happening in the obsidian plugin api, originally I learned from https://marcus.se.net/obsidian-plugin-docs/user-interface/views how to set up a view plugin, but now the following code are throwing exceptions:
```ts
await this.app.workspace.getRightLeaf(false).setViewState({
    type: type,
    active: true,
});

this.app.workspace.revealLeaf(
    this.app.workspace.getLeavesOfType(type).first()!
);
```

And the following code are printing a array of lenth 0, in which it should include the leaf this view belongs:

```ts
console.log(this.app.workspace.getLeavesOfType(TIMELINE_VIEW))
```
I need more documents to locate where the issue is, if you happen to know where the developers can get more accurate documents of obsidian, please leave a comment.

**Comment by Leonezz** [comment] 2023-05-29 02:56
Sorry for the inconvenience, but I need more digging to solve this.

**Comment by Leonezz** [comment] 2023-05-29 03:29
I have made a release that seems working, but the underlying reason why these exceptions are thrown remains unclear.

**Comment by pcause** [comment] 2023-05-29 11:41
0.1.15 doesn't fix the issue

**Comment by Leonezz** [comment] 2023-05-29 12:57
> 0.1.15 doesn't fix the issue

Can you try backup your setting and re-install?

**Comment by pcause** [comment] 2023-05-29 14:56
did it and no change

**Comment by Leonezz** [comment] 2023-05-30 04:28
Need more information since it works perfectly fine in my system.

**Comment by YIRU69** [comment] 2023-05-30 05:10
It fixs in my system.

**Comment by YIRU69** [comment] 2023-05-30 13:24
> I deleted the plugin and restarted. entered everything from scratch in options and still had the issue. remembered the comment above and turned off forward tasks from path and the exclude worked but with it enabled, the items from the excluded folders appear.

You could try togle the "forward task from task" option.

**Comment by Leonezz** [comment] 2023-05-30 13:34
> I deleted the plugin and restarted. entered everything from scratch in options and still had the issue. remembered the comment above and turned off forward tasks from path and the exclude worked but with it enabled, the items from the excluded folders appear.



> > I deleted the plugin and restarted. entered everything from scratch in options and still had the issue. remembered the comment above and turned off forward tasks from path and the exclude worked but with it enabled, the items from the excluded folders appear.
> 
> You could try togle the "forward task from task" option.

That is weird cause in my test case the exclude path option works fine. Could you please tell if there is differences that you think might cause this issue? Below is a screen record I just made in my test vault.


https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/d99747aa-107f-4353-8086-76655b68c128

**Comment by pcause** [comment] 2023-05-30 13:42
the exclude path folders have sub-folders where there are task.  so i have a templates folder and it has subfolders with other templates.  each folder has a task type template.  there was a previous issue where a folder exclusion didn't exclude all subfolders that was fixed but seems to have reappeared

**Comment by Leonezz** [comment] 2023-05-30 13:42
It comes out one detail I think might cause the issue, are there trailing '/' in your paths of the exclude path option? It might work in the earlier versions, but recently I updated the algorithm to judge if the given path is a parent path of a file, so currently the paths in the option should not have trailing '/'. @pcause @YIRU69  Could you please confirm if this is the case ?

**Comment by pcause** [comment] 2023-05-30 13:44
no trailing / and no leading /, although all path specifications start at root.  I have 2 paths specified.

**Comment by Leonezz** [comment] 2023-05-30 13:45
> the exclude path folders have sub-folders where there are task. so i have a templates folder and it has subfolders with other templates. each folder has a task type template. there was a previous issue where a folder exclusion didn't exclude all subfolders that was fixed but seems to have reappeared

This is it, I think I find the issue, will make a release to fix this soon, thanks for the information.

**Comment by Leonezz** [comment] 2023-05-30 14:17
Hi @pcause @YIRU69 @MSBack , Thanks a lot for your feedback, I hope the latest release solves the issue here. BTW if you have some test cases that you think might be helpful for testing this plugin, please comment them in #25 , that will be very helpful!

**Comment by YIRU69** [comment] 2023-05-30 14:41
It works!

**Comment by pcause** [comment] 2023-05-30 14:55
worked for me as well.  you really need to be clearer on where a leading / is needed when entering a path.

**Comment by Leonezz** [comment] 2023-05-30 15:35
Glad to hear it works! I will come  up with a document this weekend since there are already differences between options of this plugin and the original script.

**Comment by Leonezz** [comment] 2023-05-30 15:37
Closing this, please check out #25 if it may!

**Closed** 2023-05-30 15:37 UTC
Labels: bug
