### ISSUE TITLE
carry forward / overdue not working

### ISSUE THREAD

**Issue by pcause** [Leonezz/obsidian-tasks-calendar-wrapper#11] opened 2023-04-13 10:55 UTC
In options I have the carry forward for tasks set on.  In the display I see 32 todos, 3  overdue and 0 unplanned.  On the timeline I only see the items due today.  The overdue items are not displayed.  If I click the overdue button above the quick entry the overdue are not displayed.  click the todo and the todo are.  click todo again and still only today.

added an unplanned task and it is include immediately in the timeline.  clicked the unplanned button and only the unplanned was displayed.

I do have 3 overdue events.

**Comment by Leonezz** [comment] 2023-04-14 02:02
There is indeed something wrong with this option, I actually did not completely understand the semantic of it.

**Comment by pcause** [comment] 2023-04-14 11:04
what i think it means is that is a todo is not completed and its due date is before "today", show the item in "today's" items

**Comment by pcause** [comment] 2023-04-27 11:53
a small change to my thoughts.  In tasks, I and others, use the start date without a due date.  I think if something is supposed to be started by a given date and it is not marked as done it should show on the the start date the same as a task with a due date for that day, and it should be carried over until done.  You might want to make this an option (also use start date..).  Actually, tasks has a concept called "happens".  You can read about it in the docs.  You might adopt that, so that you have items that "happen" on a date or are just due on a date as choices.

**Comment by Leonezz** [comment] 2023-04-27 14:05
Thanks, it's good to know how a heavy Tasks user's thought!

**Comment by pcause** [comment] 2023-05-08 10:41
i still see 2 overdue when today focused but clicking the overdue shows nothing.  same for unscheduled.  Any thought on fixing?

**Comment by Leonezz** [comment] 2023-05-09 05:58
> i still see 2 overdue when today focused but clicking the overdue shows nothing. same for unscheduled. Any thought on fixing?

Thanks for the feedback, I see the issue is that all the status of "todo" type need a "todo" in the class names, working on a fix.

**Comment by Leonezz** [comment] 2023-05-09 06:06
> i still see 2 overdue when today focused but clicking the overdue shows nothing. same for unscheduled. Any thought on fixing?

Thanks for the feedback, I see the issue is caused by a mismatch between the filter css implementation and the definition of my code. Working on a fix.

**Comment by Leonezz** [comment] 2023-05-09 06:44
> > i still see 2 overdue when today focused but clicking the overdue shows nothing. same for unscheduled. Any thought on fixing?
> 
> Thanks for the feedback, I see the issue is caused by a mismatch between the filter css implementation and the definition of my code. Working on a fix.

I believe the latest release fixed this.

**Comment by pcause** [comment] 2023-05-09 11:01
thanks, didn't fix.  i just added a simple todo

- [ ] test 📅 2023-05-01

to my daily note (title 2023-05-09) and it is not appearing.  also the unplanned tasks count is 0 but I have 4.

**Comment by Leonezz** [comment] 2023-05-09 12:36
> thanks, didn't fix. i just added a simple todo
> 
> * [ ]  test 📅 2023-05-01
> 
> to my daily note (title 2023-05-09) and it is not appearing. also the unplanned tasks count is 0 but I have 4.

Silly me, I am using a wrong implementation for dailynote date parsering from the very beginning and I didn't realize it. I have changed to the `moment.js` for dailynote filename parsering and the example you provide should be displayed on both May, 1st and today, as shown below:

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/6d4b53de-5173-42dd-ba67-9898624b7d38)

Hope that is the behavior you are expecting!

**Comment by Leonezz** [comment] 2023-05-09 12:41
> thanks, didn't fix. i just added a simple todo
> 
> * [ ]  test 📅 2023-05-01
> 
> to my daily note (title 2023-05-09) and it is not appearing. also the unplanned tasks count is 0 but I have 4.

Also you need to turn on the `forward` option for the unplanned tasks to be displayed on today's panel, that is the behavior of the original script.

**Comment by pcause** [comment] 2023-05-09 13:02
I have had forward turned on since I initially installed

**Comment by Leonezz** [comment] 2023-05-09 14:36
> I have had forward turned on since I initially installed

That is weird, are those unplanned items also not displayed or it's just the counter number problem ?

**Comment by pcause** [comment] 2023-05-09 14:50
the unplanned items are not displayed eityher and haven't been.  i assume :unplanned" means no due date.  the items do have a start date, and it has passed, so if start date is used at all, they should be ovedue

**Comment by Leonezz** [comment] 2023-05-09 15:03
> the unplanned items are not displayed eityher and haven't been. i assume :unplanned" means no due date. the items do have a start date, and it has passed, so if start date is used at all, they should be ovedue

Alright, the issue is that if an item is given a date, then it is no longer unplanned, it will be a in-process task and it will always be displayed on the start date.

**Comment by pcause** [comment] 2023-05-09 15:27
any date?  what if it has multiple, like start and due?  if forward is set should they also be displayed on "today" is not marked due?

**Comment by Leonezz** [comment] 2023-05-10 01:22
> I am not sure the logic you describe makes sense for overdue. A task is "overdue" until done if the current date is greater than the due/start date. Something can't be overdue on its due date, as due date means, at least here in the US business "done by the end of the day" or end of the business day. When I pay a bill if it is due on May 15th it is not overdue if I pay it at 4pm May 15. I have not made a late payment (verdure payment) until May 16.

I don't see the difference between what I described and the US business definition, a task is overdue only in two cases:
1. It is marked explicitly as overdue with `>` marker,
2. It is given an earlier due date.

If the current date is exactly the given due date of an unmarked item, the status will be inferenced as `due`:

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/dea35dfe-df2d-4d2f-a008-2476e11ed716)

And if the current date is the same as the given start date, the status is `scheduled`:

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/8924541b-7d48-4635-bf1b-016a351a2b3f)

**Comment by pcause** [comment] 2023-05-19 13:38
just loaded the latest.  my overdue shows a count of zero.  when I click the overdue I now get the display for 5 tasks, which are inded overdue.  The count isn't being set.  I wonder if same for unplanned.

**Comment by pcause** [comment] 2023-05-19 13:40
Also, what does carry forward mean?  If I have that set and have overdue tasks I would have expected these tasks to be shown on today and perhaps as well on the original date.  can you either say tat is a bug or indicate in settings what this means?

**Comment by Leonezz** [comment] 2023-05-19 14:47
> Also, what does carry forward mean? If I have that set and have overdue tasks I would have expected these tasks to be shown on today and perhaps as well on the original date. can you either say tat is a bug or indicate in settings what this means?

The semantics of the original design is as you described I believe, I will implement this tomorrow.

**Comment by Leonezz** [comment] 2023-05-20 06:33
Hi @pcause , I have made a few changes to the counters and to the forward option, refer to [tag/0.1.11](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/releases/tag/0.1.11) for more details.

**Comment by pcause** [comment] 2023-05-22 10:49
yes, when i click the overdue button they show up as today.  however, I have 4 overdue tasks and the button says 2.    The task are:

- start date 5/1, no due date: shows  up as 5/1 when tasks button, but does show on overdue button
- start date 4/10, due 5/10: doesnt show up at all when tasks is selected, but does show when overdue
- start 5/1, due 5/24:  shows as 5/1 when tasks, not shown on overdue
- due 5/18, recurring monthly but due is 5/18: doesnt show when tasks, shows when overdue

so various dates types causing different meanings for filters

**Comment by Leonezz** [comment] 2023-05-22 11:23
I am not sure I understand what you mean by "when tasks button/when tasks is selected/when tasks".

**Comment by pcause** [comment] 2023-05-22 11:24
> I am not sure I understand what you mean by "when tasks button/when tasks is selected/when tasks".

referring to the tasks/overdue/unplanned buttons/filters.

**Comment by Leonezz** [comment] 2023-05-22 11:55
It makes sense if you mean "todo button/filter".
This is what I get from the five tasks you described:
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/053b6da7-ef62-480f-a249-237f299e67fa)
These are how these items setted:

- [ ] 🛫 2023-05-01 start at 5/1 #testissue11
- [ ] 🛫 2023-04-10 📅 2023-05-10 start at 4/10 due at 5/10 #testissue11
- [ ] 🛫 2023-05-01 📅 2023-05-24 start at 5/1 due at 5/24 #testissue11
- [ ] 📅 2023-05-18 due at  5/18 recurring monthly #testissue11 🔁 every month

These are what I get when todo and overdue filters enabled respectively:
![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/b840ffc2-35f4-45f5-a6ab-2fbcaf7f3f94)

![image](https://github.com/Leonezz/obsidian-tasks-calendar-wrapper/assets/33564074/2f99f42c-15b0-4ba5-be0b-f7d008c79fb7)

I can confirm an issue about the recurrence, it is not implemented yet. What others do you think are incorrect ?

**Comment by pcause** [comment] 2023-05-28 12:57
yes, i had restarted after install and had the issue.  just restarted again and the exclude box was empty, re-entered and have the issue again.

**Comment by Leonezz** [comment] 2023-05-28 13:26
> yes, i had restarted after install and had the issue. just restarted again and the exclude box was empty, re-entered and have the issue again.

Are you actually reply to #24 ? It should be fixed in v0.1.14.

**Comment by pcause** [comment] 2023-05-28 14:03
> > yes, i had restarted after install and had the issue. just restarted again and the exclude box was empty, re-entered and have the issue again.
> 
> Are you actually reply to #24 ? It should be fixed in v0.1.14.

yes

**Comment by Leonezz** [comment] 2023-05-28 14:06
Also with v0.1.14 the forward option is finally operational, can you confirm and close this?

**Closed** 2023-05-31 03:53 UTC
Labels: bug
